[theme]
base="light"
primaryColor="#6A5ACD"  # Un violet bleuté élégant
backgroundColor="#F0F8FF"  # Un bleu clair doux
secondaryBackgroundColor="#D8BFD8"  # Un violet pastel
textColor="#333333"  # Un gris foncé pour le texte
font="serif"